output_path: "./output"
symbol: resnet_101_relation.ResNet101Relation
gpus: '1'
CLASS_AGNOSTIC: false
SCALES:
- 1024
- 1600
TEST_SCALES: [[800, 1280]] # single scale testing
# TEST_SCALES: [[800, 1200], [1200, 1600], [1600, 2000], [2000, 2400]] # multi-scale testing
network:
  pretrained: "./model/pretrained_model/resnet_v1_101"
  pretrained_epoch: 0
  NMS_TARGET_THRESH: '0.5, 0.6, 0.7, 0.8, 0.9'
dataset:
  NUM_CLASSES: 3
  dataset: coco
  image_set: train
  root_path: "./data"
  test_image_set: test
  proposal: rpn
TRAIN:
  BATCH_IMAGES: 1
  lr: 0.00125 # this is for 8 gpus, if you want to use 1 gpus, the lr should be 0.01 / 8
  warmup_lr: 0.001
  warmup_step: 250
  warmup: true
  lr_step: '4,6'
  wd: 0.0001
  begin_epoch: 0
  end_epoch: 7
  RESUME: false
  RPN_NMS_THRESH: 0.7
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
  FIRST_N: 100
TEST:
  BATCH_IMAGES: 1
  # RPN proposal
  RPN_NMS_THRESH: 0.7
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
  # RPN generate proposal
  PROPOSAL_NMS_THRESH: 0.7
  PROPOSAL_PRE_NMS_TOP_N: 20000
  PROPOSAL_POST_NMS_TOP_N: 2000
  # RCNN nms
  NMS: 0.3
  test_epoch: 2
  max_per_image: 100
  # soft nms
  USE_SOFTNMS: true
  SOFTNMS_THRESH: 0.6
  LEARN_NMS_CLASS_SCORE_TH: 0.01
  FIRST_N: 100
